#SD204  TP SVD-PCA

###Exercice 1. Retour sur l’algèbre linéaire

In [173]:
import numpy as np
import time
import matplotlib.pyplot as plt
import os
#os.system('cls')

####(1)

In [174]:
mu, sigma= 0, 2
lam = 1e-5

In [175]:
#(a)
n, p = 100,2000
X = sigma * np.random.randn(n,p) + mu  # X
y = np.random.uniform(-1,1,n)          # y
Id_n = np.identity(n)                  # Id_n
Id_p = np.identity(p)                  # Id_p 
#c = np.add(a,b)
#c = np.dot(a,b)
#X_T = X.transpose()                    # X_T
#X_i = np.linalg.solve(X,Id_n)          # X_-1
left = np.dot(X.T,np.linalg.solve(np.add(np.dot(X,X.T),np.dot(lam,Id_n)),y))
right = np.linalg.solve(np.add(np.dot(X.T,X),np.dot(lam,Id_p)),np.dot(X.T,y))
result = np.allclose(left,right)
print result
# [the transpose of X: X.T]

True


In [176]:
#(b)
n, p = 2000,100
X = sigma * np.random.randn(n,p) + mu  # X
y = np.random.uniform(-1,1,n)          # y
Id_n = np.identity(n)                  # Id_n
Id_p = np.identity(p)                  # Id_p 
timeS = time.time()
left = np.dot(X.T,np.linalg.solve(np.add(np.dot(X,X.T),np.dot(lam,Id_n)),y))
timeE = time.time()
timeL = timeE - timeS                  #the run time of the method on left (2)
timeS = time.time()
right = np.linalg.solve(np.add(np.dot(X.T,X),np.dot(lam,Id_p)),np.dot(X.T,y))
timeE = time.time()
timeR = timeE - timeS                  #the run time of the method on right (2)
result = np.allclose(left,right)
print result

True


À partir de ces resultats, on voit que l'équation suivante est vraie:
$$X^T(XX^T+{\lambda}Id_n)^{-1}y=(X^TX+{\lambda}Id_p)^{-1}X^Ty$$
####(2)  RESTE A TRAVAILLER
Ici on compare le temps d'exécution de méthode gauche et méthode droite, selon la taille de n:

In [177]:
print("Pour n = 2000, p = 100:")
print("Le temps d'exécution pour la méthode gauche est %f" %timeL)
print("Le temps d'exécution pour la méthode droite est %f" %timeR)

Pour n = 2000, p = 100:
Le temps d'exécution pour la méthode gauche est 0.406000
Le temps d'exécution pour la méthode droite est 0.002000


On voit que quand on utilise la dimention de 2000, le temps d'exécution est beaucoup plus grand que la dimention de 100. Donc on choisit l'une plus petite parmi n et p pour l’astuce du noyau.

###Exercice 2. Spectre de matrice aléatoire
####(3)
Pour cette question, la loi de poisson et la loi exponentielle sont choisies. Les moyennes sont mis nulle par moins 1 pour chaque élément dans une matrice comme ci-dessous:

In [178]:
X_poi = np.random.poisson(1, size = (n,p)) - 1
X_exp = np.random.exponential(1,size = (n,p)) - 1

####(4)

In [179]:
n = 1000
p = [200,500,1000,2000]
#for i in p
a = np.matrix('1 0 0 0 2; 0 0 3 0 0; 0 0 0 0 0; 0 4 0 0 0')
print a
s= np.linalg.svd(a, full_matrices=1,compute_uv=0)
print type(s)
plt.plot([1,2,3,4])

[[1 0 0 0 2]
 [0 0 3 0 0]
 [0 0 0 0 0]
 [0 4 0 0 0]]
<type 'numpy.ndarray'>
