In [6]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.figure import Figure
%matplotlib inline
plt.close()

n, p = 5,20
X = np.random.randn(p,n)
n_iter = 100
identi_u = np.zeros(n_iter)
identi_v = np.zeros(n_iter)
#SVD
u_SVD,s,v_SVD = np.linalg.svd(X, full_matrices=1,compute_uv=1)
u_svd = u_SVD.T[0].reshape((p,1))
v_svd = v_SVD[0].reshape((n,1))
#pui
u0 = np.ones((p,1))
v0 = np.ones((n,1))
for j in range(0,n_iter):
    u = np.dot(X,v0)
    v = np.dot(X.T,u0)
    u = u*(1/np.linalg.norm(u))
    v = v*(1/np.linalg.norm(v))
    identi_u[j] = np.linalg.norm(np.subtract(u_uni,u_svd))
    identi_v[j] = np.linalg.norm(np.subtract(v_uni,v_svd))
    u0,v0 = u,v
print v, v_svd

NameError: name 'u_uni' is not defined

[[ 2.  2.  2.  2.]
 [ 2.  2.  2.  2.]
 [ 2.  2.  2.  2.]
 [ 2.  2.  2.  2.]]
